from pydantic import BaseModel, Field


class StartInterviewRequest(BaseModel):
    """Request DTO for creating an interview session."""

    job_role: str = Field(..., min_length=1, max_length=100, description="Target job role")
    direction: str | None = Field("FULL_MOCK", max_length=64, description="Interview direction")
    interviewer_mode: str | None = Field("NORMAL", max_length=64, description="Interviewer mode")
    resume_text: str | None = Field(None, description="Candidate resume text")
    duration_minutes: int = Field(
        45,
        ge=30,
        le=60,
        description="Interview duration limit in minutes",
    )


class StartInterviewResponse(BaseModel):
    """Response DTO returned after an interview session is created."""

    session_id: str = Field(..., description="Interview session identifier")
    first_question: str = Field(..., description="First question generated for the session")


class InterviewSessionResponse(BaseModel):
    """Response DTO for restoring an interview session."""

    session_id: str = Field(..., description="Interview session identifier")
    job_role: str = Field(..., description="Target job role")
    direction: str | None = Field(None, description="Interview direction")
    interviewer_mode: str | None = Field(None, description="Interviewer mode")
    status: str = Field(..., description="Interview status")
    current_round: int = Field(..., description="Current interview round")
    duration_minutes: int = Field(..., description="Interview duration limit in minutes")
    started_at: str = Field(..., description="Session start time")


class InterviewMessageResponse(BaseModel):
    """Response DTO for restoring interview messages."""

    role: str = Field(..., description="Message role")
    content: str = Field(..., description="Message content")
    round_no: int = Field(..., description="Interview round")
    created_at: str = Field(..., description="Message creation time")


class InterviewHistoryItemResponse(BaseModel):
    """Response DTO for interview history list."""

    session_id: str
    job_role: str
    direction: str | None = None
    interviewer_mode: str | None = None
    status: str
    current_round: int
    message_count: int
    answered_count: int
    duration_minutes: int
    started_at: str
    ended_at: str | None = None
    has_report: bool
    is_valid: bool = True
    overall_score: float | None = None


class LatestActiveInterviewResponse(BaseModel):
    has_active: bool
    session_id: str | None = None
    job_role: str | None = None
    direction: str | None = None
    interviewer_mode: str | None = None
    started_at: str | None = None
    answered_count: int = 0


class InterviewReviewRoundResponse(BaseModel):
    round_no: int
    question: str
    answer: str
    evaluation: str
    reference_points: list[str]
    sample_answer: str
    level: str


class InterviewReviewResponse(BaseModel):
    session_id: str
    job_role: str
    status: str
    started_at: str
    ended_at: str | None = None
    answered_count: int
    has_report: bool
    rounds: list[InterviewReviewRoundResponse]


class SubmitAnswerRequest(BaseModel):
    """Request DTO for submitting a candidate answer."""

    answer: str = Field(..., min_length=1, description="Candidate answer")


class SubmitAnswerResponse(BaseModel):
    """Response DTO returned after an answer is recorded."""

    session_id: str = Field(..., description="Interview session identifier")
    round_no: int = Field(..., description="Current interview round")
    next_question: str | None = Field(None, description="Next question generated by AI interviewer")
    is_finished: bool = Field(..., description="Whether the interview has finished")
    decision: str = Field("continue", description="LLM decision: continue/switch/end")
    reason: str | None = Field(None, description="Reason for the decision")


class FinishInterviewResponse(BaseModel):
    """Response DTO returned after an interview is manually finished."""

    session_id: str = Field(..., description="Interview session identifier")
    is_finished: bool = Field(..., description="Whether the interview has finished")


class SuccessResponse(BaseModel):
    success: bool = True


class UpdateInterviewValidityRequest(BaseModel):
    is_valid: bool
